#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: The Replication Loop

# Short bio or description (displayed in the header)
description: Collection of articles loosly focused on presenting different perspectives on the learning problem. 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/28766961?s=400&u=72d0aa76ffdca2cb71002460b6c8f64ee2782b86&v=4

remote_theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: zrobertson@stanford.edu
  github: zrobertson466920
  linkedin: www.linkedin.com/in/zachary-robertson-1286ba120
  rss: # just type anything here for a working RSS icon
  youtube: channel/UCbRdNtDRpLk7MtAD_4ntfgA
  
# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: zrobertson466920.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
mathjax: true

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
